### Sensitive analysis:

In [2]:
from sast.sast import *
from sktime.datasets import load_UCR_UEA_dataset, tsc_dataset_names
from sktime.classification.kernel_based import RocketClassifier
import time
import pandas as pd

In [3]:
ds_sens = tsc_dataset_names.univariate_equal_length
#ds_sens = ["Chinatown"]
max_ds=len(ds_sens) #exploring dataset in UEA & UCR Time Series Classification Repository
#print(ds_sens)
print(ds_sens)

['ACSF1', 'Adiac', 'ArrowHead', 'Beef', 'BeetleFly', 'BirdChicken', 'BME', 'Car', 'CBF', 'Chinatown', 'ChlorineConcentration', 'CinCECGTorso', 'Coffee', 'Computers', 'CricketX', 'CricketY', 'CricketZ', 'Crop', 'DiatomSizeReduction', 'DistalPhalanxOutlineCorrect', 'DistalPhalanxOutlineAgeGroup', 'DistalPhalanxTW', 'Earthquakes', 'ECG200', 'ECG5000', 'ECGFiveDays', 'ElectricDevices', 'EOGHorizontalSignal', 'EOGVerticalSignal', 'EthanolLevel', 'FaceAll', 'FaceFour', 'FacesUCR', 'FiftyWords', 'Fish', 'FordA', 'FordB', 'FreezerRegularTrain', 'FreezerSmallTrain', 'Fungi', 'GunPoint', 'GunPointAgeSpan', 'GunPointMaleVersusFemale', 'GunPointOldVersusYoung', 'Ham', 'HandOutlines', 'Haptics', 'Herring', 'HouseTwenty', 'InlineSkate', 'InsectEPGRegularTrain', 'InsectEPGSmallTrain', 'InsectWingbeatSound', 'ItalyPowerDemand', 'LargeKitchenAppliances', 'Lightning2', 'Lightning7', 'Mallat', 'Meat', 'MedicalImages', 'MiddlePhalanxOutlineCorrect', 'MiddlePhalanxOutlineAgeGroup', 'MiddlePhalanxTW', 'MixedShapesRegularTrain', 'MixedShapesSmallTrain', 'MoteStrain', 'NonInvasiveFetalECGThorax1', 'NonInvasiveFetalECGThorax2', 'OliveOil', 'OSULeaf', 'PhalangesOutlinesCorrect', 'Phoneme', 'PigAirwayPressure', 'PigArtPressure', 'PigCVP', 'Plane', 'PowerCons', 'ProximalPhalanxOutlineCorrect', 'ProximalPhalanxOutlineAgeGroup', 'ProximalPhalanxTW', 'RefrigerationDevices', 'Rock', 'ScreenType', 'SemgHandGenderCh2', 'SemgHandMovementCh2', 'SemgHandSubjectCh2', 'ShapeletSim', 'ShapesAll', 'SmallKitchenAppliances', 'SmoothSubspace', 'SonyAIBORobotSurface1', 'SonyAIBORobotSurface2', 'StarlightCurves', 'Strawberry', 'SwedishLeaf', 'Symbols', 'SyntheticControl', 'ToeSegmentation1', 'ToeSegmentation2', 'Trace', 'TwoLeadECG', 'TwoPatterns', 'UMD', 'UWaveGestureLibraryAll', 'UWaveGestureLibraryX', 'UWaveGestureLibraryY', 'UWaveGestureLibraryZ', 'Wafer', 'Wine', 'WordSynonyms', 'Worms', 'WormsTwoClass', 'Yoga']

In [4]:
#ds='Chinatown' # Chosing a dataset from # Number of classes to consider
runs = 1
range_total = [1 ]
#list
df_result = {}
list_score = []
list_time = []
list_dataset = []
list_hyperparameter = []
list_method = []
list_rpoint = []
list_nb_per_class = []

for ds in ds_sens:
    print("ds="+ds)
    X_train, y_train = load_UCR_UEA_dataset(name=ds, extract_path='data', split="train", return_type="numpy2d")
    X_test, y_test = load_UCR_UEA_dataset(name=ds, extract_path='data', split="test", return_type="numpy2d")
    for i in range(runs):
        """
        start = time.time()
        rocket= RocketClassifier(num_kernels=10_000)
        rocket.fit(X_train,y_train)
        end = time.time()
        list_score.append(rocket.score(X_test,y_test))
        list_time.append(end-start)
        list_dataset.append(ds)
        list_hyperparameter.append("num_kernels=10_000")
        list_rpoint.append(str(0))
        list_nb_per_class.append(str(0))
        list_method.append("Rocket")
        """
        for p in range_total:
            for g in range_total:
                if p ==0:
                    p=1
                if g ==0:
                    g=1
                start = time.time()
                random_state = None
                rsast_ridge = RSAST(n_random_points=p,nb_inst_per_class=g, classifier=RidgeClassifierCV())
                rsast_ridge.fit(X_train, y_train)
                end = time.time()
                list_score.append(rsast_ridge.score(X_test,y_test))
                list_time.append(end-start)
                list_dataset.append(ds)
                list_hyperparameter.append("n_random_points="+str(p)+" nb_inst_per_class="+str(g))
                list_rpoint.append(str(p))
                list_nb_per_class.append(str(g))
                list_method.append("Rsast")
                print("n_random_points="+str(p)+" nb_inst_per_class="+str(g))

    df_result['score']=list_score
    df_result['time']=list_time
    df_result['dataset']=list_dataset
    df_result['hyperparameter']=list_hyperparameter
    df_result['rpoint']=list_rpoint
    df_result['nb_per_class']=list_nb_per_class
    df_result['method']=list_method

ds=ACSF1

In [7]:
df_result=pd.DataFrame(df_result)
df_result.to_excel("df_tunning_hyper.xlsx") 
df_result

,score,time,dataset,hyperparameter,rpoint,nb_per_class,method
0,0.982507,7.489812,Chinatown,num_kernels=10_000,0,0,Rocket
1,0.807580,3.328784,Chinatown,n_random_points=1 nb_inst_per_class=1,1,1,Rsast
2,0.930029,0.048441,Chinatown,n_random_points=1 nb_inst_per_class=10,1,10,Rsast
3,0.944606,0.019941,Chinatown,n_random_points=10 nb_inst_per_class=1,10,1,Rsast
4,0.965015,0.130159,Chinatown,n_random_points=10 nb_inst_per_class=10,10,10,Rsast
5,0.982507,7.290069,Chinatown,num_kernels=10_000,0,0,Rocket
6,0.897959,0.012969,Chinatown,n_random_points=1 nb_inst_per_class=1,1,1,Rsast
7,0.950437,0.049898,Chinatown,n_random_points=1 nb_inst_per_class=10,1,10,Rsast
8,0.947522,0.015981,Chinatown,n_random_points=10 nb_inst_per_class=1,10,1,Rsast
9,0.979592,0.125178,Chinatown,n_random_points=10 nb_inst_per_class=10,10,10,Rsast
10,0.982507,7.257863,Chinatown,num_kernels=10_000,0,0,Rocket
11,0.932945,0.011968,Chinatown,n_random_points=1 nb_inst_per_class=1,1,1,Rsast
12,0.956268,0.044879,Chinatown,n_random_points=1 nb_inst_per_class=10,1,10,Rsast
13,0.906706,0.017941,Chinatown,n_random_points=10 nb_inst_per_class=1,10,1,Rsast
14,0.979592,0.119680,Chinatown,n_random_points=10 nb_inst_per_class=10,10,10,Rsast
15,0.982507,7.377132,Chinatown,num_kernels=10_000,0,0,Rocket
16,0.921283,0.011000,Chinatown,n_random_points=1 nb_inst_per_class=1,1,1,Rsast
17,0.941691,0.049899,Chinatown,n_random_points=1 nb_inst_per_class=10,1,10,Rsast
18,0.956268,0.020943,Chinatown,n_random_points=10 nb_inst_per_class=1,10,1,Rsast
19,0.985423,0.120677,Chinatown,n_random_points=10 nb_inst_per_class=10,10,10,Rsast
20,0.982507,7.476187,Chinatown,num_kernels=10_000,0,0,Rocket
21,0.775510,0.011999,Chinatown,n_random_points=1 nb_inst_per_class=1,1,1,Rsast
22,0.950437,0.050864,Chinatown,n_random_points=1 nb_inst_per_class=10,1,10,Rsast
23,0.938776,0.019949,Chinatown,n_random_points=10 nb_inst_per_class=1,10,1,Rsast
24,0.979592,0.125614,Chinatown,n_random_points=10 nb_inst_per_class=10,10,10,Rsast