### Sensitive analysis:

In [2]:
from sast.sast import *
from sktime.datasets import load_UCR_UEA_dataset
from sktime.classification.kernel_based import RocketClassifier
import time
import numpy as np
import pandas as pd
from sast.sast import znormalize_array,from_2d_array_to_nested
import matplotlib.pyplot as plt
from sktime.datasets import tsc_dataset_names

In [3]:
ds_sens = tsc_dataset_names.univariate_equal_length
ds_sens = ["Chinatown","BirdChicken","Coffee"]
max_ds=len(ds_sens) #exploring dataset in UEA & UCR Time Series Classification Repository
#print(ds_sens)
print(ds_sens)

['Chinatown', 'BirdChicken', 'Coffee']

In [4]:
#ds='Chinatown' # Chosing a dataset from # Number of classes to consider
runs = 1
range_total = [1 ,10 , 100]
#list
df_result = {}
list_score = []
list_time = []
list_dataset = []
list_hyperparameter = []
list_method = []
list_rpoint = []
list_nb_per_class = []

for ds in ds_sens:
    X_train, y_train = load_UCR_UEA_dataset(name=ds, extract_path='data', split="train", return_type="numpy2d")
    X_test, y_test = load_UCR_UEA_dataset(name=ds, extract_path='data', split="test", return_type="numpy2d")
    for i in range(runs):
        start = time.time()
        rocket= RocketClassifier(num_kernels=10_000)
        rocket.fit(X_train,y_train)
        end = time.time()
        list_score.append(rocket.score(X_test,y_test))
        list_time.append(end-start)
        list_dataset.append(ds)
        list_hyperparameter.append("num_kernels=10_000")
        list_rpoint.append(str(0))
        list_nb_per_class.append(str(0))
        list_method.append("Rocket")
        for p in range_total:
            for g in range_total:
                if p ==0:
                    p=1
                if g ==0:
                    g=1
                start = time.time()
                random_state = None
                rsast_ridge = RSAST(n_random_points=p,nb_inst_per_class=g, classifier=RidgeClassifierCV())
                rsast_ridge.fit(X_train, y_train)
                end = time.time()
                list_score.append(rsast_ridge.score(X_test,y_test))
                list_time.append(end-start)
                list_dataset.append(ds)
                list_hyperparameter.append("n_random_points="+str(p)+" nb_inst_per_class="+str(g))
                list_rpoint.append(str(p))
                list_nb_per_class.append(str(g))
                list_method.append("Rsast")
                print("n_random_points="+str(p)+" nb_inst_per_class="+str(g))

    df_result['score']=list_score
    df_result['time']=list_time
    df_result['dataset']=list_dataset
    df_result['hyperparameter']=list_hyperparameter
    df_result['rpoint']=list_rpoint
    df_result['nb_per_class']=list_nb_per_class
    df_result['method']=list_method

n_random_points=1 nb_inst_per_class=1
n_random_points=1 nb_inst_per_class=10
n_random_points=1 nb_inst_per_class=100
n_random_points=10 nb_inst_per_class=1
n_random_points=10 nb_inst_per_class=10
n_random_points=10 nb_inst_per_class=100
n_random_points=100 nb_inst_per_class=1
n_random_points=100 nb_inst_per_class=10
n_random_points=100 nb_inst_per_class=100
n_random_points=1 nb_inst_per_class=1

In [ ]:
df_result=pd.DataFrame(df_result)
df_result.to_excel("df_tunning_hyper.xlsx") 
df_result

,score,time,dataset,hyperparameter,rpoint,nb_per_class,method
0,0.982507,7.969090,Chinatown,num_kernels=10_000,0,0,Rocket
1,0.877551,0.012979,Chinatown,n_random_points=1 nb_inst_per_class=1,1,1,Rsast
2,0.970845,0.047904,Chinatown,n_random_points=1 nb_inst_per_class=10,1,10,Rsast
3,0.970845,0.016964,Chinatown,n_random_points=10 nb_inst_per_class=1,10,1,Rsast
4,0.976676,0.114693,Chinatown,n_random_points=10 nb_inst_per_class=10,10,10,Rsast
5,0.982507,7.296936,Chinatown,num_kernels=10_000,0,0,Rocket
6,0.918367,0.012927,Chinatown,n_random_points=1 nb_inst_per_class=1,1,1,Rsast
7,0.921283,0.045878,Chinatown,n_random_points=1 nb_inst_per_class=10,1,10,Rsast
8,0.778426,0.017971,Chinatown,n_random_points=10 nb_inst_per_class=1,10,1,Rsast
9,0.976676,0.112698,Chinatown,n_random_points=10 nb_inst_per_class=10,10,10,Rsast
10,0.982507,7.165920,Chinatown,num_kernels=10_000,0,0,Rocket
11,0.962099,0.012967,Chinatown,n_random_points=1 nb_inst_per_class=1,1,1,Rsast
12,0.965015,0.044878,Chinatown,n_random_points=1 nb_inst_per_class=10,1,10,Rsast
13,0.862974,0.016955,Chinatown,n_random_points=10 nb_inst_per_class=1,10,1,Rsast
14,0.959184,0.111701,Chinatown,n_random_points=10 nb_inst_per_class=10,10,10,Rsast
15,0.982507,7.071098,Chinatown,num_kernels=10_000,0,0,Rocket
16,0.778426,0.012995,Chinatown,n_random_points=1 nb_inst_per_class=1,1,1,Rsast
17,0.932945,0.047871,Chinatown,n_random_points=1 nb_inst_per_class=10,1,10,Rsast
18,0.976676,0.020939,Chinatown,n_random_points=10 nb_inst_per_class=1,10,1,Rsast
19,0.982507,0.111701,Chinatown,n_random_points=10 nb_inst_per_class=10,10,10,Rsast
20,0.982507,6.879356,Chinatown,num_kernels=10_000,0,0,Rocket
21,0.877551,0.011968,Chinatown,n_random_points=1 nb_inst_per_class=1,1,1,Rsast
22,0.950437,0.048901,Chinatown,n_random_points=1 nb_inst_per_class=10,1,10,Rsast
23,0.941691,0.021966,Chinatown,n_random_points=10 nb_inst_per_class=1,10,1,Rsast
24,0.982507,0.118684,Chinatown,n_random_points=10 nb_inst_per_class=10,10,10,Rsast
25,0.982507,8.235323,Chinatown,num_kernels=10_000,0,0,Rocket
26,0.959184,0.014959,Chinatown,n_random_points=1 nb_inst_per_class=1,1,1,Rsast
27,0.930029,0.043881,Chinatown,n_random_points=1 nb_inst_per_class=10,1,10,Rsast
28,0.854227,0.017952,Chinatown,n_random_points=10 nb_inst_per_class=1,10,1,Rsast
29,0.973761,0.119681,Chinatown,n_random_points=10 nb_inst_per_class=10,10,10,Rsast
30,0.982507,8.204300,Chinatown,num_kernels=10_000,0,0,Rocket
31,0.772595,0.033908,Chinatown,n_random_points=1 nb_inst_per_class=1,1,1,Rsast
32,0.947522,0.073805,Chinatown,n_random_points=1 nb_inst_per_class=10,1,10,Rsast
33,0.932945,0.019948,Chinatown,n_random_points=10 nb_inst_per_class=1,10,1,Rsast
34,0.967930,0.129653,Chinatown,n_random_points=10 nb_inst_per_class=10,10,10,Rsast
35,0.982507,7.248633,Chinatown,num_kernels=10_000,0,0,Rocket
36,0.871720,0.016981,Chinatown,n_random_points=1 nb_inst_per_class=1,1,1,Rsast
37,0.944606,0.050894,Chinatown,n_random_points=1 nb_inst_per_class=10,1,10,Rsast
38,0.889213,0.023937,Chinatown,n_random_points=10 nb_inst_per_class=1,10,1,Rsast
39,0.973761,0.163563,Chinatown,n_random_points=10 nb_inst_per_class=10,10,10,Rsast
40,0.982507,7.981403,Chinatown,num_kernels=10_000,0,0,Rocket
41,0.889213,0.013961,Chinatown,n_random_points=1 nb_inst_per_class=1,1,1,Rsast
42,0.930029,0.045885,Chinatown,n_random_points=1 nb_inst_per_class=10,1,10,Rsast
43,0.953353,0.016955,Chinatown,n_random_points=10 nb_inst_per_class=1,10,1,Rsast
44,0.982507,0.116688,Chinatown,n_random_points=10 nb_inst_per_class=10,10,10,Rsast
45,0.982507,8.873954,Chinatown,num_kernels=10_000,0,0,Rocket
46,0.944606,0.013958,Chinatown,n_random_points=1 nb_inst_per_class=1,1,1,Rsast
47,0.938776,0.046875,Chinatown,n_random_points=1 nb_inst_per_class=10,1,10,Rsast
48,0.965015,0.023936,Chinatown,n_random_points=10 nb_inst_per_class=1,10,1,Rsast
49,0.976676,0.117810,Chinatown,n_random_points=10 nb_inst_per_class=10,10,10,Rsast