### Sensitive analysis:

In [1]:
from sast.sast import *
from sktime.datasets import load_UCR_UEA_dataset, tsc_dataset_names
from sktime.classification.kernel_based import RocketClassifier
import time
import pandas as pd

/home/nirojasvar/anaconda3/envs/rsast_env/lib/python3.10/site-packages/mass_ts/_mass_ts.py:17: UserWarning: GPU support will not work. You must pip install mass-ts[gpu].
  warnings.warn(

In [12]:
ds_sens = tsc_dataset_names.univariate_equal_length
#ds_sens = ['ACSF1', 'Adiac', 'ArrowHead', 'Beef', 'BeetleFly', 'BirdChicken', 'BME', 'Car', 'CBF', 'Chinatown', 'ChlorineConcentration', 'CinCECGTorso', 'Coffee']
ds_sens = ['Chinatown']
max_ds=len(ds_sens) #exploring dataset in UEA & UCR Time Series Classification Repository
#print(ds_sens)
print(ds_sens)

['Chinatown', 'ACSF1']

In [14]:
#ds='Chinatown' # Chosing a dataset from # Number of classes to consider
runs = 2
range_total = [1,10,100,1000,10000 ]
#list
df_result = {}
list_score = []
list_time = []
list_dataset = []
list_hyperparameter = []
list_method = []
list_rpoint = []
list_nb_per_class = []

for ds in ds_sens:
    print("ds="+ds)
    X_train, y_train = load_UCR_UEA_dataset(name=ds, extract_path='data', split="train", return_type="numpy2d")
    X_test, y_test = load_UCR_UEA_dataset(name=ds, extract_path='data', split="test", return_type="numpy2d")
    for i in range(runs):
        """
        start = time.time()
        rocket= RocketClassifier(num_kernels=10_000)
        rocket.fit(X_train,y_train)
        end = time.time()
        list_score.append(rocket.score(X_test,y_test))
        list_time.append(end-start)
        list_dataset.append(ds)
        list_hyperparameter.append("num_kernels=10_000")
        list_rpoint.append(str(0))
        list_nb_per_class.append(str(0))
        list_method.append("Rocket")
        """
        for p in range_total:
            for g in range_total:
                if p ==0:
                    p=1
                if g ==0:
                    g=1
                start = time.time()
                random_state = None
                rsast_ridge = RSAST(n_random_points=p,nb_inst_per_class=g, classifier=RidgeClassifierCV())
                rsast_ridge.fit(X_train, y_train)
                end = time.time()
                list_score.append(rsast_ridge.score(X_test,y_test))
                list_time.append(end-start)
                list_dataset.append(ds)
                list_hyperparameter.append("n_random_points="+str(p)+" nb_inst_per_class="+str(g))
                list_rpoint.append(str(p))
                list_nb_per_class.append(str(g))
                list_method.append("Rsast")
                print("n_random_points="+str(p)+" nb_inst_per_class="+str(g))

df_result['accuracy']=list_score
df_result['time']=list_time
df_result['dataset_name']=list_dataset
df_result['classifier_name']=list_hyperparameter
df_result['rpoint']=list_rpoint
df_result['nb_per_class']=list_nb_per_class
df_result['method']=list_method

ds=Chinatown
n_random_points=1 nb_inst_per_class=1
n_random_points=1 nb_inst_per_class=10
n_random_points=1 nb_inst_per_class=100
n_random_points=1 nb_inst_per_class=1000
n_random_points=1 nb_inst_per_class=10000
n_random_points=10 nb_inst_per_class=1
n_random_points=10 nb_inst_per_class=10
n_random_points=10 nb_inst_per_class=100
n_random_points=10 nb_inst_per_class=1000
n_random_points=10 nb_inst_per_class=10000
n_random_points=100 nb_inst_per_class=1
n_random_points=100 nb_inst_per_class=10
n_random_points=100 nb_inst_per_class=100

In [9]:
df_result=pd.DataFrame(df_result)
df_result.to_csv("df_tunning_hyper.csv") 
#df_result

,score,time,dataset,hyperparameter,rpoint,nb_per_class,method
0,0.725948,0.019580,Chinatown,n_random_points=1 nb_inst_per_class=1,1,1,Rsast
1,0.979592,0.067711,Chinatown,n_random_points=1 nb_inst_per_class=10,1,10,Rsast
2,0.883382,0.107767,Chinatown,n_random_points=1 nb_inst_per_class=100,1,100,Rsast
3,0.921283,0.085062,Chinatown,n_random_points=10 nb_inst_per_class=1,10,1,Rsast
4,0.982507,0.162297,Chinatown,n_random_points=10 nb_inst_per_class=10,10,10,Rsast
5,0.982507,0.160658,Chinatown,n_random_points=10 nb_inst_per_class=100,10,100,Rsast
6,0.918367,0.132625,Chinatown,n_random_points=100 nb_inst_per_class=1,100,1,Rsast
7,0.979592,0.917010,Chinatown,n_random_points=100 nb_inst_per_class=10,100,10,Rsast
8,0.985423,0.914228,Chinatown,n_random_points=100 nb_inst_per_class=100,100,100,Rsast
9,0.772595,0.054867,Chinatown,n_random_points=1 nb_inst_per_class=1,1,1,Rsast
10,0.967930,0.050122,Chinatown,n_random_points=1 nb_inst_per_class=10,1,10,Rsast
11,0.877551,0.066108,Chinatown,n_random_points=1 nb_inst_per_class=100,1,100,Rsast
12,0.935860,0.070635,Chinatown,n_random_points=10 nb_inst_per_class=1,10,1,Rsast
13,0.979592,0.162776,Chinatown,n_random_points=10 nb_inst_per_class=10,10,10,Rsast
14,0.970845,0.151114,Chinatown,n_random_points=10 nb_inst_per_class=100,10,100,Rsast
15,0.938776,0.099918,Chinatown,n_random_points=100 nb_inst_per_class=1,100,1,Rsast
16,0.982507,0.910301,Chinatown,n_random_points=100 nb_inst_per_class=10,100,10,Rsast
17,0.985423,0.915028,Chinatown,n_random_points=100 nb_inst_per_class=100,100,100,Rsast
18,0.597668,0.029505,Chinatown,n_random_points=1 nb_inst_per_class=1,1,1,Rsast
19,0.962099,0.090801,Chinatown,n_random_points=1 nb_inst_per_class=10,1,10,Rsast
20,0.953353,0.084795,Chinatown,n_random_points=1 nb_inst_per_class=100,1,100,Rsast
21,0.956268,0.050838,Chinatown,n_random_points=10 nb_inst_per_class=1,10,1,Rsast
22,0.970845,0.142951,Chinatown,n_random_points=10 nb_inst_per_class=10,10,10,Rsast
23,0.979592,0.157171,Chinatown,n_random_points=10 nb_inst_per_class=100,10,100,Rsast
24,0.947522,0.102024,Chinatown,n_random_points=100 nb_inst_per_class=1,100,1,Rsast
25,0.985423,0.904367,Chinatown,n_random_points=100 nb_inst_per_class=10,100,10,Rsast
26,0.985423,0.911189,Chinatown,n_random_points=100 nb_inst_per_class=100,100,100,Rsast
27,0.932945,0.048101,Chinatown,n_random_points=1 nb_inst_per_class=1,1,1,Rsast
28,0.959184,0.069744,Chinatown,n_random_points=1 nb_inst_per_class=10,1,10,Rsast
29,0.950437,0.079957,Chinatown,n_random_points=1 nb_inst_per_class=100,1,100,Rsast
30,0.848397,0.035892,Chinatown,n_random_points=10 nb_inst_per_class=1,10,1,Rsast
31,0.979592,0.147812,Chinatown,n_random_points=10 nb_inst_per_class=10,10,10,Rsast
32,0.985423,0.180067,Chinatown,n_random_points=10 nb_inst_per_class=100,10,100,Rsast
33,0.938776,0.101672,Chinatown,n_random_points=100 nb_inst_per_class=1,100,1,Rsast
34,0.982507,0.918360,Chinatown,n_random_points=100 nb_inst_per_class=10,100,10,Rsast
35,0.985423,0.899452,Chinatown,n_random_points=100 nb_inst_per_class=100,100,100,Rsast
36,0.661808,0.019638,Chinatown,n_random_points=1 nb_inst_per_class=1,1,1,Rsast
37,0.924198,0.047716,Chinatown,n_random_points=1 nb_inst_per_class=10,1,10,Rsast
38,0.959184,0.094751,Chinatown,n_random_points=1 nb_inst_per_class=100,1,100,Rsast
39,0.944606,0.058728,Chinatown,n_random_points=10 nb_inst_per_class=1,10,1,Rsast
40,0.982507,0.145757,Chinatown,n_random_points=10 nb_inst_per_class=10,10,10,Rsast
41,0.979592,0.175811,Chinatown,n_random_points=10 nb_inst_per_class=100,10,100,Rsast
42,0.927114,0.102355,Chinatown,n_random_points=100 nb_inst_per_class=1,100,1,Rsast
43,0.982507,0.920646,Chinatown,n_random_points=100 nb_inst_per_class=10,100,10,Rsast
44,0.982507,0.915537,Chinatown,n_random_points=100 nb_inst_per_class=100,100,100,Rsast

In [11]:
# create a pivot table
pivot_table = pd.pivot_table(df_result, values='score', index=['rpoint'], columns=['nb_per_class'], aggfunc='mean')

print(pivot_table)

nb_per_class         1        10       100
rpoint
1             0.738192  0.958601  0.924781
10            0.921283  0.979009  0.979592
100           0.934111  0.982507  0.984840